[package]
name = "at-test"
version = "0.1.0"
authors = ["majorz"]
edition = "2018"

[dependencies]
serialport = { git = "https://gitlab.com/susurrus/serialport-rs.git" }
libc = "*"
anyhow = "*"
nom = "*"
num_enum = "*"
